name: build
on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        default: '17'
        required: false
        type: string
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.java-version }}
          cache: 'maven'
      - uses: lorislab/install-samo-action@v2
      - name: Version info
        run: |
          samo project version
          samo project version --version=release
      - name: Build project
        run: mvn --no-transfer-progress --batch-mode --errors clean package
