name: build-release
on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        default: '17'
        required: false
        type: string
env:
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
jobs:
  build:
    name: build release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up java
        uses: actions/setup-java@v4
        with:
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_KEY_SECRET }}
          gpg-passphrase:  GPG_PASSPHRASE
          distribution: 'zulu'
          java-version: ${{ inputs.java-version }}
          cache: 'maven'
      - name: Set project version
        run: mvn --no-transfer-progress --batch-mode --errors versions:set -DnewVersion=${{ github.ref_name }}
      - name: Deploy release
        run: mvn --no-transfer-progress --batch-mode --errors deploy -DskipTests -Prelease        
      - uses: lorislab/install-changelog-action@v1
      - name: Create changelog
        run: changelog generate --create-release --close-version --file .github/changelog.yaml
        env:
          CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}

