name: build-release
on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        default: '17'
        required: false
        type: string
jobs:
  build:
    name: build release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          server-id: ossrh
          server-username: ${{ secrets.OOSRH_USERNAME }}
          server-password: ${{ secrets.OOSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_KEY_SECRET }}
          gpg-passphrase:  ${{ secrets.GPG_PASSPHRASE }}
          distribution: 'zulu'
          java-version: ${{ inputs.java-version }}
          cache: 'maven'
      - name: Set project version
        run: mvn versions:set -DnewVersion=${{ github.ref_name }}
      - name: Deploy release
        run: mvn deploy -DskipTests -Prelease
      - name: Create release
        uses: lorislab/changelog-action@v1.0.0
        with:
          args: generate --create-release --close-version --file .github/changelog.yaml
        env:
          CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
