name: documentation
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TKIT_CI_PAT }}
          repository: 1000kit/1000kit.github.io
          event-type: dispatch-build-website
